
The following have been reloaded with a version change:
  1) java/jdk-1.8u112 => java/jdk-17.0.7

no change     /n/app/miniconda3/23.1.0/condabin/conda
no change     /n/app/miniconda3/23.1.0/bin/conda
no change     /n/app/miniconda3/23.1.0/bin/conda-env
no change     /n/app/miniconda3/23.1.0/bin/activate
no change     /n/app/miniconda3/23.1.0/bin/deactivate
no change     /n/app/miniconda3/23.1.0/etc/profile.d/conda.sh
no change     /n/app/miniconda3/23.1.0/etc/fish/conf.d/conda.fish
no change     /n/app/miniconda3/23.1.0/shell/condabin/Conda.psm1
no change     /n/app/miniconda3/23.1.0/shell/condabin/conda-hook.ps1
no change     /n/app/miniconda3/23.1.0/lib/python3.10/site-packages/xontrib/conda.xsh
no change     /n/app/miniconda3/23.1.0/etc/profile.d/conda.csh
no change     /home/kel331/.bashrc
No action taken.

The following have been reloaded with a version change:
  1) java/jdk-17.0.7 => java/jdk-1.8u112

/home/kel331/.conda/envs/cellprofiler/lib/python3.10/site-packages/scipy/ndimage/_measurements.py:1407: RuntimeWarning: invalid value encountered in divide
  results = [sum(input * grids[dir].astype(float), labels, index) / normalizer
slurmstepd: error: *** JOB 33071195 ON compute-a-16-167 CANCELLED AT 2024-02-28T16:49:55 DUE TO TIME LIMIT ***
